# Generated by Django 4.2.1 on 2025-01-17 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OpenBench', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='scale_method',
            field=models.CharField(choices=[('DEV', 'DEV'), ('BASE', 'BASE'), ('BOTH', 'BOTH')], default='BASE', max_length=16),
        ),
        migrations.AddField(
            model_name='test',
            name='scale_nps',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='test',
            name='base_netname',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='test',
            name='base_network',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='test',
            name='dev_netname',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='test',
            name='dev_network',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='test',
            name='genfens_args',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
